import { Contracts, apiResponseWrapper, mockDataWrapper } from '@/connections';
import { EmptyRequestSchema } from '@/contracts/common';
import { PATHS } from '@/routes/paths';
import { BestSellersResponseSchema, BigOffersResponseSchema } from './schemas';

const BIG_OFFERS_MOCK = [
  {
    id: '1',
    image: '/images/landing/big-offer/01.png',
    imageAlt: 'پکیج صرفه‌جویی خانوار',
    title: 'پکیج صرفه‌جویی خانوار',
    startBadge: 'اقساط ۵ ماهه',
    endBadge: '۲۰٪ تخفیف',
    priceLabel: 'قیمت از',
    price: '۴۵۰٬۰۰۰',
    stockNote: 'در ۷۲ فروشگاه',
    actionLabel: 'خرید',
    href: PATHS.WHOLESALE.OFFERS,
  },
  {
    id: '2',
    image: '/images/landing/big-offer/02.png',
    imageAlt: 'سبد پروتئین ویژه',
    title: 'سبد پروتئین ویژه',
    startBadge: 'ارسال رایگان',
    endBadge: '۱۵٪ تخفیف',
    priceLabel: 'قیمت از',
    price: '۸۹۰٬۰۰۰',
    stockNote: 'در ۲۴ فروشگاه',
    actionLabel: 'خرید',
    href: PATHS.WHOLESALE.OFFERS,
  },
  {
    id: '3',
    image: '/images/landing/big-offer/03.png',
    imageAlt: 'خشکبار درجه یک',
    title: 'خشکبار درجه یک',
    startBadge: 'اصالت کالا',
    endBadge: '۱۰٪ تخفیف',
    priceLabel: 'قیمت از',
    price: '۳۲۰٬۰۰۰',
    stockNote: 'در ۱۵۰ فروشگاه',
    actionLabel: 'خرید',
    href: PATHS.WHOLESALE.OFFERS,
  },
  {
    id: '4',
    image: '/images/landing/big-offer/04.png',
    imageAlt: 'نوشیدنی‌های گرم زمستانی',
    title: 'نوشیدنی‌های گرم زمستانی',
    startBadge: 'اقساط ۵ ماهه',
    endBadge: '۲۵٪ تخفیف',
    priceLabel: 'قیمت از',
    price: '۱۲۰٬۰۰۰',
    stockNote: 'در ۳۶ فروشگاه',
    actionLabel: 'خرید',
    href: PATHS.WHOLESALE.OFFERS,
  },
  {
    id: '5',
    image: '/images/landing/big-offer/05.png',
    imageAlt: 'لوازم پذیرایی',
    title: 'لوازم پذیرایی',
    startBadge: 'پرفروش',
    endBadge: '۳۰٪ تخفیف',
    priceLabel: 'قیمت از',
    price: '۲۶۰٬۰۰۰',
    stockNote: 'در ۵۸ فروشگاه',
    actionLabel: 'خرید',
    href: PATHS.WHOLESALE.OFFERS,
  },
];

// Mirrors BIG_OFFERS_MOCK until the real endpoint provides its own payload.
const BEST_SELLERS_MOCK = [
  {
    id: '11',
    image: '/images/landing/big-offer/01.png',
    imageAlt: 'پکیج صرفه‌جویی خانوار',
    title: 'پکیج صرفه‌جویی خانوار',
    startBadge: 'اقساط ۵ ماهه',
    endBadge: '۲۰٪ تخفیف',
    priceLabel: 'قیمت از',
    price: '۴۵۰٬۰۰۰',
    stockNote: 'در ۷۲ فروشگاه',
    actionLabel: 'خرید',
    href: PATHS.WHOLESALE.BEST_SELLERS,
  },
  {
    id: '12',
    image: '/images/landing/big-offer/02.png',
    imageAlt: 'سبد پروتئین ویژه',
    title: 'سبد پروتئین ویژه',
    startBadge: 'ارسال رایگان',
    endBadge: '۱۵٪ تخفیف',
    priceLabel: 'قیمت از',
    price: '۸۹۰٬۰۰۰',
    stockNote: 'در ۲۴ فروشگاه',
    actionLabel: 'خرید',
    href: PATHS.WHOLESALE.BEST_SELLERS,
  },
  {
    id: '13',
    image: '/images/landing/big-offer/03.png',
    imageAlt: 'خشکبار درجه یک',
    title: 'خشکبار درجه یک',
    startBadge: 'اصالت کالا',
    endBadge: '۱۰٪ تخفیف',
    priceLabel: 'قیمت از',
    price: '۳۲۰٬۰۰۰',
    stockNote: 'در ۱۵۰ فروشگاه',
    actionLabel: 'خرید',
    href: PATHS.WHOLESALE.BEST_SELLERS,
  },
  {
    id: '14',
    image: '/images/landing/big-offer/04.png',
    imageAlt: 'نوشیدنی‌های گرم زمستانی',
    title: 'نوشیدنی‌های گرم زمستانی',
    startBadge: 'اقساط ۵ ماهه',
    endBadge: '۲۵٪ تخفیف',
    priceLabel: 'قیمت از',
    price: '۱۲۰٬۰۰۰',
    stockNote: 'در ۳۶ فروشگاه',
    actionLabel: 'خرید',
    href: PATHS.WHOLESALE.BEST_SELLERS,
  },
  {
    id: '15',
    image: '/images/landing/big-offer/05.png',
    imageAlt: 'لوازم پذیرایی',
    title: 'لوازم پذیرایی',
    startBadge: 'پرفروش',
    endBadge: '۳۰٪ تخفیف',
    priceLabel: 'قیمت از',
    price: '۲۶۰٬۰۰۰',
    stockNote: 'در ۵۸ فروشگاه',
    actionLabel: 'خرید',
    href: PATHS.WHOLESALE.BEST_SELLERS,
  },
];

export const bannersContracts = {
  banners: {
    getBigOffers: {
      method: 'GET',
      path: '/banners/big-offer',
      request: EmptyRequestSchema,
      response: apiResponseWrapper(BigOffersResponseSchema),
      mockData: mockDataWrapper(BIG_OFFERS_MOCK),
    },
    getBestSellers: {
      method: 'GET',
      path: '/banners/best-sellers',
      request: EmptyRequestSchema,
      response: apiResponseWrapper(BestSellersResponseSchema),
      mockData: mockDataWrapper(BEST_SELLERS_MOCK),
    },
  },
} as const satisfies Contracts;
