import { Contracts, apiResponseWrapper, mockDataWrapper } from '@/connections';
import { EmptyRequestSchema } from '@/contracts/common';
import { CitiesListResponseSchema, type City } from './schemas';

/**
 * Every Iranian city the picker offers, grouped by province so the flattening
 * below can disambiguate the names that repeat across provinces (نورآباد in
 * both فارس and لرستان, …). Provinces are ordered by how often they get
 * picked — the first entry doubles as `CitySelect`'s fallback value.
 */
const CITIES_BY_PROVINCE: ReadonlyArray<{
  slug: string;
  name: string;
  cities: ReadonlyArray<readonly [value: string, label: string]>;
}> = [
  {
    slug: 'tehran',
    name: 'تهران',
    cities: [
      ['tehran', 'تهران'],
      ['rey', 'ری'],
      ['tajrish', 'تجریش'],
      ['eslamshahr', 'اسلامشهر'],
      ['shahriar', 'شهریار'],
      ['malard', 'ملارد'],
      ['qods', 'قدس'],
      ['robat-karim', 'رباط‌کریم'],
      ['pakdasht', 'پاکدشت'],
      ['varamin', 'ورامین'],
      ['qarchak', 'قرچک'],
      ['pishva', 'پیشوا'],
      ['damavand', 'دماوند'],
      ['firuzkuh', 'فیروزکوه'],
      ['pardis', 'پردیس'],
      ['baharestan', 'بهارستان'],
      ['nasimshahr', 'نسیم‌شهر'],
      ['salehieh', 'صالحیه'],
      ['chahardangeh', 'چهاردانگه'],
      ['bagher-shahr', 'باقرشهر'],
      ['kahrizak', 'کهریزک'],
      ['hasanabad', 'حسن‌آباد'],
      ['andisheh', 'اندیشه'],
      ['shahedshahr', 'شاهدشهر'],
      ['sabashahr', 'صباشهر'],
      ['ferdosiyeh', 'فردوسیه'],
      ['vahidiyeh', 'وحیدیه'],
      ['golestan-city', 'گلستان'],
      ['lavasan', 'لواسان'],
      ['rudehen', 'رودهن'],
      ['bumehen', 'بومهن'],
      ['abali', 'آبعلی'],
      ['absard', 'آبسرد'],
      ['arjmand', 'ارجمند'],
      ['sharifabad', 'شریف‌آباد'],
      ['javadabad', 'جوادآباد'],
      ['safadasht', 'صفادشت'],
      ['baghestan', 'باغستان'],
      ['shemshak', 'شمشک'],
    ],
  },
  {
    slug: 'alborz',
    name: 'البرز',
    cities: [
      ['karaj', 'کرج'],
      ['fardis', 'فردیس'],
      ['nazarabad', 'نظرآباد'],
      ['hashtgerd', 'هشتگرد'],
      ['eshtehard', 'اشتهارد'],
      ['mahdasht', 'ماهدشت'],
      ['mohammadshahr', 'محمدشهر'],
      ['meshkin-dasht', 'مشکین‌دشت'],
      ['kamalshahr', 'کمال‌شهر'],
      ['garmdareh', 'گرمدره'],
      ['chaharbagh', 'چهارباغ'],
      ['taleqan', 'طالقان'],
      ['asara', 'آسارا'],
      ['tankaman', 'تنکمان'],
      ['kuhsar', 'کوهسار'],
    ],
  },
  {
    slug: 'isfahan',
    name: 'اصفهان',
    cities: [
      ['isfahan', 'اصفهان'],
      ['kashan', 'کاشان'],
      ['khomeynishahr', 'خمینی‌شهر'],
      ['najafabad', 'نجف‌آباد'],
      ['shahinshahr', 'شاهین‌شهر'],
      ['shahreza', 'شهرضا'],
      ['mobarakeh', 'مبارکه'],
      ['fuladshahr', 'فولادشهر'],
      ['zarrinshahr', 'زرین‌شهر'],
      ['falavarjan', 'فلاورجان'],
      ['golpayegan', 'گلپایگان'],
      ['khansar', 'خوانسار'],
      ['natanz', 'نطنز'],
      ['ardestan', 'اردستان'],
      ['naein', 'نائین'],
      ['semirom', 'سمیرم'],
      ['daran', 'داران'],
      ['fereydunshahr', 'فریدون‌شهر'],
      ['chadegan', 'چادگان'],
      ['dehaqan', 'دهاقان'],
      ['tiran', 'تیران'],
      ['buin-miandasht', 'بوئین‌میاندشت'],
      ['aran-va-bidgol', 'آران و بیدگل'],
      ['badrud', 'بادرود'],
      ['dolatabad', 'دولت‌آباد'],
      ['khorzuq', 'خورزوق'],
      ['gaz', 'گز'],
      ['dorcheh', 'درچه'],
      ['qahderijan', 'قهدریجان'],
      ['bagh-bahadoran', 'باغ‌بهادران'],
      ['varzaneh', 'ورزنه'],
      ['khur', 'خور'],
      ['zavareh', 'زواره'],
      ['dehaq', 'دهق'],
      ['alavijeh', 'علویجه'],
      ['kelishad', 'کلیشاد'],
      ['harand', 'هرند'],
      ['kuhpayeh', 'کوهپایه'],
      ['meymeh', 'میمه'],
      ['vazvan', 'وزوان'],
      ['abrisham', 'ابریشم'],
      ['nikabad', 'نیک‌آباد'],
    ],
  },
  {
    slug: 'razavi-khorasan',
    name: 'خراسان رضوی',
    cities: [
      ['mashhad', 'مشهد'],
      ['neyshabur', 'نیشابور'],
      ['sabzevar', 'سبزوار'],
      ['torbat-heydarieh', 'تربت حیدریه'],
      ['torbat-jam', 'تربت جام'],
      ['kashmar', 'کاشمر'],
      ['quchan', 'قوچان'],
      ['gonabad', 'گناباد'],
      ['chenaran', 'چناران'],
      ['dargaz', 'درگز'],
      ['sarakhs', 'سرخس'],
      ['fariman', 'فریمان'],
      ['khaf', 'خواف'],
      ['roshtkhar', 'رشتخوار'],
      ['bardaskan', 'بردسکن'],
      ['taybad', 'تایباد'],
      ['bakharz', 'باخرز'],
      ['joghatai', 'جغتای'],
      ['jovein', 'جوین'],
      ['khalilabad', 'خلیل‌آباد'],
      ['davarzan', 'داورزن'],
      ['zaveh', 'زاوه'],
      ['salehabad', 'صالح‌آباد'],
      ['firuzeh', 'فیروزه'],
      ['kalat', 'کلات'],
      ['feyzabad', 'فیض‌آباد'],
      ['bajestan', 'بجستان'],
      ['torqabeh', 'طرقبه'],
      ['shandiz', 'شاندیز'],
      ['sheshtamad', 'ششتمد'],
    ],
  },
  {
    slug: 'fars',
    name: 'فارس',
    cities: [
      ['shiraz', 'شیراز'],
      ['marvdasht', 'مرودشت'],
      ['jahrom', 'جهرم'],
      ['fasa', 'فسا'],
      ['kazerun', 'کازرون'],
      ['lar', 'لار'],
      ['darab', 'داراب'],
      ['firuzabad', 'فیروزآباد'],
      ['abadeh', 'آباده'],
      ['eqlid', 'اقلید'],
      ['neyriz', 'نی‌ریز'],
      ['estahban', 'استهبان'],
      ['lamerd', 'لامرد'],
      ['nurabad', 'نورآباد'],
      ['sepidan', 'سپیدان'],
      ['zarqan', 'زرقان'],
      ['sadra', 'صدرا'],
      ['kharameh', 'خرامه'],
      ['sarvestan', 'سروستان'],
      ['qir', 'قیر'],
      ['farashband', 'فراشبند'],
      ['khonj', 'خنج'],
      ['gerash', 'گراش'],
      ['mohr', 'مهر'],
      ['arsanjan', 'ارسنجان'],
      ['bavanat', 'بوانات'],
      ['pasargad', 'پاسارگاد'],
      ['rostam', 'رستم'],
      ['kavar', 'کوار'],
      ['zarrindasht', 'زرین‌دشت'],
      ['beyza', 'بیضا'],
      ['sheshdeh', 'ششده'],
    ],
  },
  {
    slug: 'khuzestan',
    name: 'خوزستان',
    cities: [
      ['ahvaz', 'اهواز'],
      ['abadan', 'آبادان'],
      ['khorramshahr', 'خرمشهر'],
      ['dezful', 'دزفول'],
      ['andimeshk', 'اندیمشک'],
      ['shushtar', 'شوشتر'],
      ['behbahan', 'بهبهان'],
      ['mahshahr', 'ماهشهر'],
      ['izeh', 'ایذه'],
      ['shush', 'شوش'],
      ['masjed-soleyman', 'مسجدسلیمان'],
      ['ramhormoz', 'رامهرمز'],
      ['omidiyeh', 'امیدیه'],
      ['bandar-imam', 'بندر امام خمینی'],
      ['hendijan', 'هندیجان'],
      ['shadegan', 'شادگان'],
      ['baghmalek', 'باغ‌ملک'],
      ['lali', 'لالی'],
      ['andika', 'اندیکا'],
      ['gotvand', 'گتوند'],
      ['haftkel', 'هفتکل'],
      ['susangerd', 'سوسنگرد'],
      ['hoveyzeh', 'هویزه'],
      ['karun', 'کارون'],
      ['bavi', 'باوی'],
      ['hamidiyeh', 'حمیدیه'],
      ['ramshir', 'رامشیر'],
      ['aghajari', 'آغاجاری'],
    ],
  },
  {
    slug: 'east-azerbaijan',
    name: 'آذربایجان شرقی',
    cities: [
      ['tabriz', 'تبریز'],
      ['maragheh', 'مراغه'],
      ['marand', 'مرند'],
      ['mianeh', 'میانه'],
      ['ahar', 'اهر'],
      ['bonab', 'بناب'],
      ['shabestar', 'شبستر'],
      ['sarab', 'سراب'],
      ['azarshahr', 'آذرشهر'],
      ['osku', 'اسکو'],
      ['hashtrud', 'هشترود'],
      ['bostanabad', 'بستان‌آباد'],
      ['jolfa', 'جلفا'],
      ['kaleybar', 'کلیبر'],
      ['malekan', 'ملکان'],
      ['heris', 'هریس'],
      ['ajabshir', 'عجب‌شیر'],
      ['varzaqan', 'ورزقان'],
      ['charuymaq', 'چاراویماق'],
      ['khodaafarin', 'خداآفرین'],
      ['horand', 'هوراند'],
      ['ilkhchi', 'ایلخچی'],
      ['sardrud', 'سردرود'],
      ['basmenj', 'باسمنج'],
      ['tikmehdash', 'تیکمه‌داش'],
    ],
  },
  {
    slug: 'west-azerbaijan',
    name: 'آذربایجان غربی',
    cities: [
      ['urmia', 'ارومیه'],
      ['khoy', 'خوی'],
      ['miandoab', 'میاندوآب'],
      ['mahabad', 'مهاباد'],
      ['bukan', 'بوکان'],
      ['salmas', 'سلماس'],
      ['naqadeh', 'نقده'],
      ['piranshahr', 'پیرانشهر'],
      ['sardasht', 'سردشت'],
      ['maku', 'ماکو'],
      ['shahindezh', 'شاهین‌دژ'],
      ['takab', 'تکاب'],
      ['oshnavieh', 'اشنویه'],
      ['siahcheshmeh', 'سیه‌چشمه'],
      ['poldasht', 'پلدشت'],
      ['showt', 'شوط'],
      ['chaypareh', 'چایپاره'],
      ['baruq', 'باروق'],
    ],
  },
  {
    slug: 'kerman',
    name: 'کرمان',
    cities: [
      ['kerman', 'کرمان'],
      ['rafsanjan', 'رفسنجان'],
      ['sirjan', 'سیرجان'],
      ['bam', 'بم'],
      ['jiroft', 'جیرفت'],
      ['zarand', 'زرند'],
      ['kahnuj', 'کهنوج'],
      ['bardsir', 'بردسیر'],
      ['baft', 'بافت'],
      ['shahrebabak', 'شهربابک'],
      ['ravar', 'راور'],
      ['anar', 'انار'],
      ['anbarabad', 'عنبرآباد'],
      ['manujan', 'منوجان'],
      ['qaleganj', 'قلعه‌گنج'],
      ['rudbar-jonub', 'رودبار جنوب'],
      ['fahraj', 'فهرج'],
      ['rigan', 'ریگان'],
      ['narmashir', 'نرماشیر'],
      ['orzuiyeh', 'ارزوئیه'],
      ['rabor', 'رابر'],
      ['faryab', 'فاریاب'],
      ['kuhbanan', 'کوهبنان'],
    ],
  },
  {
    slug: 'sistan-baluchestan',
    name: 'سیستان و بلوچستان',
    cities: [
      ['zahedan', 'زاهدان'],
      ['zabol', 'زابل'],
      ['iranshahr', 'ایرانشهر'],
      ['chabahar', 'چابهار'],
      ['saravan', 'سراوان'],
      ['khash', 'خاش'],
      ['nikshahr', 'نیک‌شهر'],
      ['konarak', 'کنارک'],
      ['sarbaz', 'سرباز'],
      ['delgan', 'دلگان'],
      ['mehrestan', 'مهرستان'],
      ['fanuj', 'فنوج'],
      ['qasr-e-qand', 'قصرقند'],
      ['hirmand', 'هیرمند'],
      ['zehak', 'زهک'],
      ['nimruz', 'نیمروز'],
      ['mirjaveh', 'میرجاوه'],
      ['bampur', 'بمپور'],
      ['rask', 'راسک'],
      ['sib-suran', 'سیب و سوران'],
      ['hamun', 'هامون'],
    ],
  },
  {
    slug: 'north-khorasan',
    name: 'خراسان شمالی',
    cities: [
      ['bojnurd', 'بجنورد'],
      ['shirvan', 'شیروان'],
      ['esfarayen', 'اسفراین'],
      ['ashkhaneh', 'آشخانه'],
      ['garmeh', 'گرمه'],
      ['jajarm', 'جاجرم'],
      ['faruj', 'فاروج'],
      ['raz-jargalan', 'راز و جرگلان'],
    ],
  },
  {
    slug: 'south-khorasan',
    name: 'خراسان جنوبی',
    cities: [
      ['birjand', 'بیرجند'],
      ['qaen', 'قائن'],
      ['ferdows', 'فردوس'],
      ['tabas', 'طبس'],
      ['nehbandan', 'نهبندان'],
      ['sarbisheh', 'سربیشه'],
      ['darmian', 'درمیان'],
      ['boshruyeh', 'بشرویه'],
      ['khusf', 'خوسف'],
      ['zirkuh', 'زیرکوه'],
      ['sarayan', 'سرایان'],
    ],
  },
  {
    slug: 'gilan',
    name: 'گیلان',
    cities: [
      ['rasht', 'رشت'],
      ['anzali', 'بندر انزلی'],
      ['lahijan', 'لاهیجان'],
      ['langarud', 'لنگرود'],
      ['astara', 'آستارا'],
      ['talesh', 'تالش'],
      ['somesara', 'صومعه‌سرا'],
      ['fuman', 'فومن'],
      ['rudsar', 'رودسر'],
      ['astaneh-ashrafiyeh', 'آستانه اشرفیه'],
      ['rudbar', 'رودبار'],
      ['masal', 'ماسال'],
      ['shaft', 'شفت'],
      ['siahkal', 'سیاهکل'],
      ['amlash', 'املش'],
      ['rezvanshahr', 'رضوانشهر'],
      ['khomam', 'خمام'],
      ['kuchesfahan', 'کوچصفهان'],
      ['lashtnesha', 'لشت‌نشا'],
      ['masuleh', 'ماسوله'],
      ['manjil', 'منجیل'],
      ['rostamabad', 'رستم‌آباد'],
      ['kelachay', 'کلاچای'],
      ['chaboksar', 'چابکسر'],
    ],
  },
  {
    slug: 'mazandaran',
    name: 'مازندران',
    cities: [
      ['sari', 'ساری'],
      ['babol', 'بابل'],
      ['amol', 'آمل'],
      ['qaemshahr', 'قائم‌شهر'],
      ['babolsar', 'بابلسر'],
      ['chalus', 'چالوس'],
      ['nowshahr', 'نوشهر'],
      ['tonekabon', 'تنکابن'],
      ['ramsar', 'رامسر'],
      ['behshahr', 'بهشهر'],
      ['neka', 'نکا'],
      ['juybar', 'جویبار'],
      ['polsefid', 'پل‌سفید'],
      ['mahmudabad', 'محمودآباد'],
      ['fereydunkenar', 'فریدونکنار'],
      ['nur', 'نور'],
      ['abbasabad', 'عباس‌آباد'],
      ['galugah', 'گلوگاه'],
      ['kiakola', 'کیاکلا'],
      ['miandorud', 'میاندورود'],
      ['kelardasht', 'کلاردشت'],
      ['marzanabad', 'مرزن‌آباد'],
      ['zirab', 'زیرآب'],
      ['sorkhrud', 'سرخ‌رود'],
      ['izadshahr', 'ایزدشهر'],
    ],
  },
  {
    slug: 'golestan',
    name: 'گلستان',
    cities: [
      ['gorgan', 'گرگان'],
      ['gonbad-kavus', 'گنبد کاووس'],
      ['aliabad-katul', 'علی‌آباد کتول'],
      ['aqqala', 'آق‌قلا'],
      ['kordkuy', 'کردکوی'],
      ['bandar-torkaman', 'بندر ترکمن'],
      ['bandar-gaz', 'بندر گز'],
      ['minudasht', 'مینودشت'],
      ['azadshahr', 'آزادشهر'],
      ['ramian', 'رامیان'],
      ['kalaleh', 'کلاله'],
      ['gomishan', 'گمیشان'],
      ['maraveh-tappeh', 'مراوه‌تپه'],
      ['galikash', 'گالیکش'],
    ],
  },
  {
    slug: 'qom',
    name: 'قم',
    cities: [
      ['qom', 'قم'],
      ['salafchegan', 'سلفچگان'],
      ['jafariyeh', 'جعفریه'],
      ['dastjerd', 'دستجرد'],
      ['kahak', 'کهک'],
      ['qanavat', 'قنوات'],
    ],
  },
  {
    slug: 'markazi',
    name: 'مرکزی',
    cities: [
      ['arak', 'اراک'],
      ['saveh', 'ساوه'],
      ['khomeyn', 'خمین'],
      ['mahallat', 'محلات'],
      ['delijan', 'دلیجان'],
      ['shazand', 'شازند'],
      ['tafresh', 'تفرش'],
      ['ashtian', 'آشتیان'],
      ['komijan', 'کمیجان'],
      ['mamuniyeh', 'مامونیه'],
      ['farmahin', 'فرمهین'],
      ['khondab', 'خنداب'],
      ['mohajeran', 'مهاجران'],
    ],
  },
  {
    slug: 'hamadan',
    name: 'همدان',
    cities: [
      ['hamadan', 'همدان'],
      ['malayer', 'ملایر'],
      ['nahavand', 'نهاوند'],
      ['tuyserkan', 'تویسرکان'],
      ['asadabad', 'اسدآباد'],
      ['bahar', 'بهار'],
      ['kabudarahang', 'کبودرآهنگ'],
      ['razan', 'رزن'],
      ['famenin', 'فامنین'],
      ['dargazin', 'درگزین'],
      ['lalejin', 'لالجین'],
      ['qahavand', 'قهاوند'],
    ],
  },
  {
    slug: 'kermanshah',
    name: 'کرمانشاه',
    cities: [
      ['kermanshah', 'کرمانشاه'],
      ['eslamabad-gharb', 'اسلام‌آباد غرب'],
      ['harsin', 'هرسین'],
      ['kangavar', 'کنگاور'],
      ['sonqor', 'سنقر'],
      ['paveh', 'پاوه'],
      ['javanrud', 'جوانرود'],
      ['sahneh', 'صحنه'],
      ['sarpol-zahab', 'سرپل ذهاب'],
      ['qasr-shirin', 'قصر شیرین'],
      ['gilan-gharb', 'گیلانغرب'],
      ['ravansar', 'روانسر'],
      ['salas-babajani', 'ثلاث باباجانی'],
      ['dalahu', 'دالاهو'],
      ['kerend', 'کرند غرب'],
    ],
  },
  {
    slug: 'kordestan',
    name: 'کردستان',
    cities: [
      ['sanandaj', 'سنندج'],
      ['saqqez', 'سقز'],
      ['marivan', 'مریوان'],
      ['baneh', 'بانه'],
      ['bijar', 'بیجار'],
      ['qorveh', 'قروه'],
      ['kamyaran', 'کامیاران'],
      ['divandarreh', 'دیواندره'],
      ['dehgolan', 'دهگلان'],
      ['sarvabad', 'سروآباد'],
    ],
  },
  {
    slug: 'lorestan',
    name: 'لرستان',
    cities: [
      ['khorramabad', 'خرم‌آباد'],
      ['borujerd', 'بروجرد'],
      ['dorud', 'دورود'],
      ['aligudarz', 'الیگودرز'],
      ['kuhdasht', 'کوهدشت'],
      ['nurabad', 'نورآباد'],
      ['azna', 'ازنا'],
      ['poldokhtar', 'پلدختر'],
      ['aleshtar', 'الشتر'],
      ['romeshkan', 'رومشکان'],
    ],
  },
  {
    slug: 'ilam',
    name: 'ایلام',
    cities: [
      ['ilam', 'ایلام'],
      ['dehloran', 'دهلران'],
      ['abdanan', 'آبدانان'],
      ['eyvan', 'ایوان'],
      ['mehran', 'مهران'],
      ['darreshahr', 'دره‌شهر'],
      ['sarableh', 'سرابله'],
      ['badreh', 'بدره'],
      ['malekshahi', 'ملکشاهی'],
      ['chavar', 'چوار'],
    ],
  },
  {
    slug: 'bushehr',
    name: 'بوشهر',
    cities: [
      ['bushehr', 'بوشهر'],
      ['borazjan', 'برازجان'],
      ['genaveh', 'بندر گناوه'],
      ['deylam', 'بندر دیلم'],
      ['kangan', 'کنگان'],
      ['asaluyeh', 'عسلویه'],
      ['khormuj', 'خورموج'],
      ['jam', 'جم'],
      ['ahram', 'اهرم'],
      ['bandar-rig', 'بندر ریگ'],
      ['delvar', 'دلوار'],
      ['bordekhun', 'بردخون'],
      ['alishahr', 'عالی‌شهر'],
      ['choghadak', 'چغادک'],
    ],
  },
  {
    slug: 'hormozgan',
    name: 'هرمزگان',
    cities: [
      ['bandar-abbas', 'بندرعباس'],
      ['minab', 'میناب'],
      ['qeshm', 'قشم'],
      ['kish', 'کیش'],
      ['bandar-lengeh', 'بندر لنگه'],
      ['rudan', 'رودان'],
      ['hajiabad', 'حاجی‌آباد'],
      ['bastak', 'بستک'],
      ['parsian', 'پارسیان'],
      ['jask', 'جاسک'],
      ['sirik', 'سیریک'],
      ['bashagard', 'بشاگرد'],
      ['khamir', 'بندر خمیر'],
      ['abumusa', 'ابوموسی'],
      ['dargahan', 'درگهان'],
      ['hormoz', 'هرمز'],
    ],
  },
  {
    slug: 'yazd',
    name: 'یزد',
    cities: [
      ['yazd', 'یزد'],
      ['meybod', 'میبد'],
      ['ardakan', 'اردکان'],
      ['bafq', 'بافق'],
      ['mehriz', 'مهریز'],
      ['taft', 'تفت'],
      ['abarkuh', 'ابرکوه'],
      ['ashkezar', 'اشکذر'],
      ['marvast', 'مروست'],
      ['bahabad', 'بهاباد'],
      ['zarch', 'زارچ'],
      ['hamidia', 'حمیدیا'],
    ],
  },
  {
    slug: 'semnan',
    name: 'سمنان',
    cities: [
      ['semnan', 'سمنان'],
      ['shahrud', 'شاهرود'],
      ['damghan', 'دامغان'],
      ['garmsar', 'گرمسار'],
      ['mehdishahr', 'مهدی‌شهر'],
      ['sorkheh', 'سرخه'],
      ['aradan', 'آرادان'],
      ['mayamey', 'میامی'],
      ['bastam', 'بسطام'],
      ['eyvanekey', 'ایوانکی'],
      ['shahmirzad', 'شهمیرزاد'],
    ],
  },
  {
    slug: 'zanjan',
    name: 'زنجان',
    cities: [
      ['zanjan', 'زنجان'],
      ['abhar', 'ابهر'],
      ['khoramdarreh', 'خرمدره'],
      ['qeydar', 'قیدار'],
      ['abbar', 'آب‌بر'],
      ['mahneshan', 'ماه‌نشان'],
      ['ijrud', 'ایجرود'],
      ['soltaniyeh', 'سلطانیه'],
      ['hidaj', 'هیدج'],
      ['saeenqaleh', 'صائین‌قلعه'],
    ],
  },
  {
    slug: 'qazvin',
    name: 'قزوین',
    cities: [
      ['qazvin', 'قزوین'],
      ['takestan', 'تاکستان'],
      ['abyek', 'آبیک'],
      ['buin-zahra', 'بوئین‌زهرا'],
      ['alvand', 'الوند'],
      ['mohammadiyeh', 'محمدیه'],
      ['eqbaliyeh', 'اقبالیه'],
      ['avaj', 'آوج'],
      ['ziaabad', 'ضیاءآباد'],
      ['shal', 'شال'],
      ['danesfahan', 'دانسفهان'],
    ],
  },
  {
    slug: 'ardabil',
    name: 'اردبیل',
    cities: [
      ['ardabil', 'اردبیل'],
      ['parsabad', 'پارس‌آباد'],
      ['meshginshahr', 'مشگین‌شهر'],
      ['khalkhal', 'خلخال'],
      ['germi', 'گرمی'],
      ['bilesavar', 'بیله‌سوار'],
      ['namin', 'نمین'],
      ['nir', 'نیر'],
      ['kowsar', 'کوثر'],
      ['sarein', 'سرعین'],
      ['aslanduz', 'اصلاندوز'],
      ['hir', 'هیر'],
    ],
  },
  {
    slug: 'chaharmahal-bakhtiari',
    name: 'چهارمحال و بختیاری',
    cities: [
      ['shahrekord', 'شهرکرد'],
      ['borujen', 'بروجن'],
      ['lordegan', 'لردگان'],
      ['farsan', 'فارسان'],
      ['ardal', 'اردل'],
      ['kuhrang', 'کوهرنگ'],
      ['saman', 'سامان'],
      ['ben', 'بن'],
      ['shalamzar', 'شلمزار'],
      ['khanmirza', 'خانمیرزا'],
      ['farrokhshahr', 'فرخ‌شهر'],
      ['junqan', 'جونقان'],
      ['sureshjan', 'سورشجان'],
    ],
  },
  {
    slug: 'kohgiluyeh-boyerahmad',
    name: 'کهگیلویه و بویراحمد',
    cities: [
      ['yasuj', 'یاسوج'],
      ['dogonbadan', 'دوگنبدان'],
      ['dehdasht', 'دهدشت'],
      ['likak', 'لیکک'],
      ['sisakht', 'سی‌سخت'],
      ['charam', 'چرام'],
      ['basht', 'باشت'],
      ['landeh', 'لنده'],
      ['margun', 'مارگون'],
    ],
  },
];

const cityLabelCounts = new Map<string, number>();

for (const province of CITIES_BY_PROVINCE) {
  for (const [, label] of province.cities) {
    cityLabelCounts.set(label, (cityLabelCounts.get(label) ?? 0) + 1);
  }
}

/**
 * Flat picker payload. A city name that exists in more than one province is
 * qualified on BOTH sides — the label so the list never shows two
 * indistinguishable rows, the value so every option stays uniquely keyed.
 */
export const CITIES_MOCK: City[] = CITIES_BY_PROVINCE.flatMap((province) =>
  province.cities.map(([value, label]) => {
    const ambiguous = (cityLabelCounts.get(label) ?? 0) > 1;

    return {
      value: ambiguous ? `${value}-${province.slug}` : value,
      label: ambiguous ? `${label} (${province.name})` : label,
    };
  }),
);

/** Provinces in the same popularity order — the profile's «محل کسب‌وکار» picker. */
export const PROVINCES_MOCK: City[] = CITIES_BY_PROVINCE.map((province) => ({
  value: province.slug,
  label: province.name,
}));

export const citiesContracts = {
  cities: {
    getList: {
      method: 'GET',
      path: '/cities',
      request: EmptyRequestSchema,
      response: apiResponseWrapper(CitiesListResponseSchema),
      mockData: mockDataWrapper(CITIES_MOCK),
    },

    /** `GET /provinces` — NOT LIVE YET; `useProvinces` forces the mock. */
    getProvinces: {
      method: 'GET',
      path: '/provinces',
      request: EmptyRequestSchema,
      response: apiResponseWrapper(CitiesListResponseSchema),
      mockData: mockDataWrapper(PROVINCES_MOCK),
    },
  },
} as const satisfies Contracts;
